### ISSUE TITLE
Using "full-bleed" image causes unwanted horizontal scrollbar

### ISSUE THREAD

**Issue by Staindk** [kaushikgopal/henry-jekyll#9]
Hi,

I like your theme and the features you've built into it.

Saw [the post about it](https://blog.jkl.gg/henry-jekyll-theme) had a horizontal scrollbar for me and wondered what would be causing it - and as soon as I saw the `full-bleed` img class I knew it would likely be that.

`100vh` in CSS seems to equate to your full viewport _including the space a vertical scrollbar takes up_ - so if there is a vertical scrollbar, a `100vh` element will cause a vertical-scrollbar-width horizontal scrollbar to show up. Very possible that this isn't an issue on all browsers, but on Chrome it is (and has been for a very long time, AFAIK).

Adding `overflow-x: hidden;` to the `body` CSS essentially solves the issue - for me, on that blog post, on desktop. Not sure if it's the ideal fix though as it may affect other parts of the site and with it you're also technically cutting a sliver off the right of each `full-bleed` pic.

Screenshot: 
![image](https://user-images.githubusercontent.com/19654761/113227678-89856280-9293-11eb-9186-9bed697f270f.png)

**Comment by kaushikgopal** [comment]
🙏🏽 thanks @Staindk - indeed there was a slight miscalculation. #10 should fix this.
